### PR TITLE
Add profiles for iOS/macOS

### LINKED ISSUE #14: How to use DoT or DoH on iOS 14
It seems iOS 14 does support DoT and DoH however the configuration appears to require some sort of binary profile to take affect. There is no simple UI setting.

According to the requester such an example profiles can be found here: https://adguard.com/en/blog/encrypted-dns-ios-14.html

It is desirable to describe how to change iOS settings to use our secure DNS resolvers and optionally do provide such profiles (if needed). This may even obsolete DNSCloak.

### PR DESCRIPTION
**Pull request by lorenzschmid**
Adds profiles for iOS and macOS devices, closes #14

On the added profiles:

- Based on the profiles by [paulmillr/encrypted-dns](https://github.com/paulmillr/encrypted-dns), official [documentation from Apple](https://developer.apple.com/documentation/devicemanagement/dnssettings)
- Sets the system default DNS server for all networks (WiFI and cellular)
- Sets the connection to the DNS server (TLS or HTTPS)
- The random identifier (`PayloadIdentifier` and `PayloadUUID`) are randomly generated: The actual content is unimportant, but must be globally unique (see [documentation](https://developer.apple.com/documentation/devicemanagement/configuring_multiple_devices_using_profiles#overview)). All other settings should be obvious

### CODE REVIEW

**Comment by ryru** [comment]
Thank you for this PR! :+1: 

Technically this looks good to me. Although I can not test it myself so I asked the requester of this feature for some testing and feedback. I'll merge this as soon as this person (and maybe others too) like it.

**Comment by lorenzschmid** [comment]
No worries! I tried it on my phone by sniffing with Wireshark. I could not see any communication via port 53 but neither did I for port 853. But since I am not a Wireshark expert I might have missed something. When using [cloudflare's tool](https://cloudflare-dns.com/help/) it showed at least the updated DNS server IPs.

**Comment by muuvmuuv** [comment]
@lorenzschmid Tested your profile and tried the Cloudflare tool but cannot see updated DNS server ips nor does it say "Using DNS over HTTPS Yes". It just shows 1.1.1.1 and 1.0.0.1 together with some IPv6 (not those in the config file).

**Comment by muuvmuuv** [comment]
I did a few more tests mentioned here: https://forum.kuketz-blog.de/viewtopic.php?t=1361

|Test|Result|
|-|-|
|http://dnssec.vs.uni-due.de/|Passed|
|http://en.conn.internet.nl/connection/|Passed|
|https://dnsleaktest.com/|Passed, only shows: res1.digitale-gesellschaft.ch|
|https://www.grc.com/dns/dns.htm|Passed|

So it seems that its working :)

IMG_1380

**Comment by lorenzschmid** [comment]
> I did a few more tests mentioned here: https://forum.kuketz-blog.de/viewtopic.php?t=1361
> ...
> So it seems that its working :)

That's great to know, thanks a lot for verifying @muuvmuuv !

@ryru shall we merge?

**Comment by ryru** [comment]
Looks good!
Thank you @lorenzschmid and @muuvmuuv

**Pull request merged**
